### ISSUE TITLE
Can Compiling FPS Plus Public

### ISSUE THREAD

**Issue by ModdingGaming10** [ThatRozebudDude/FPS-Plus-Public#139] opened 2024-12-06 21:26 UTC
i can Compiling FPS-Plus-Public because of this error 

C:/Users/OneDrive/Desktop/FNF/FPS-Plus-Public-master/FPS-Plus-Public-master/.haxelib/polymod/git/polymod/hscript/_internal/PolymodAbstractScriptClass.hx:5: characters 37-55 : Type not found : PolymodScriptClass

someone please help me

**Comment by moxie-coder** [comment] 2024-12-06 21:45
duplicate of #137

**Comment by ModdingGaming10** [comment] 2024-12-08 18:57
i not see how to fix the Issue 

> duplicate of #137

i not see how to fix the Issue

**Comment by ThatRozebudDude** [comment] 2024-12-14 05:37
Try reinstalling the deleting the `.haxelib` and reinstalling them with hmm

**Comment by ModdingGaming10** [comment] 2024-12-14 18:05
i got C:/Users/???/OneDrive/Desktop/fnf engine/FPS-Plus-Public-master/FPS-Plus-Public-master/.haxelib/polymod/git/polymod/hscript/_internal/PolymodAbstractScriptClass.hx:5: characters 37-55 : Type not found : PolymodScriptClass

**Comment by moxie-coder** [comment] 2024-12-14 18:34
maybe don’t try to compile in OneDrive? You know just as a heads up

**Comment by ModdingGaming10** [comment] 2024-12-14 18:50
i can try

**Comment by ModdingGaming10** [comment] 2024-12-14 19:11
i got 
source/modding/GlobalScriptingTypesMacro.hx:22: Applying scripting types to ScriptedSpriteGroup
C:/Users/???/Downloads/FPS-Plus-Public-master/FPS-Plus-Public-master/.haxelib/flxanimate/git/flxanimate/animate/FlxElement.hx:149: characters 39-40 : Unexpected ?

**Comment by ModdingGaming10** [comment] 2024-12-14 19:13
i can see if i can set up build tools in part 8

**Comment by ModdingGaming10** [comment] 2024-12-14 22:20
it doesn't working

**Comment by ModdingGaming10** [comment] 2024-12-14 22:21
it doesn't working

**Closed** 2024-12-15 16:36 UTC
