### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by ModdingGaming10** [ThatRozebudDude/FPS-Plus-Public#102] opened 2024-10-19 02:51 UTC
source/note/Note.hx:120: characters 10-15 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)
source/note/Note.hx:120: characters 10-15 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/note/Note.hx:127: characters 11-16 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)
source/note/Note.hx:127: characters 11-16 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/note/Note.hx:148: characters 10-15 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)
source/note/Note.hx:148: characters 10-15 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/note/Note.hx:154: characters 10-15 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)
source/note/Note.hx:154: characters 10-15 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/AtlasSprite.hx:34: characters 14-21 : flxanimate.animate.FlxAnim has no field onFrame
source/AtlasSprite.hx:48: characters 72-76 : Null<String> has no field name
source/Character.hx:458: characters 10-16 : Warning : Potential typo detected (expected similar values are characters.AnimType.frames)
source/AtlasSprite.hx:104: characters 72-76 : Null<String> has no field name
source/PlayState.hx:1062: characters 10-15 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/PlayState.hx:1069: characters 10-15 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/PlayState.hx:1076: characters 10-15 : Warning : Potential typo detected (expected similar values are frames). Consider using `var frame` instead
source/AtlasSprite.hx:195: characters 14-20 : flxanimate.animate.FlxAnim has no field resume
source/AtlasSprite.hx:241: characters 40-47 : flixel.math.FlxMatrix should be Int
source/AtlasSprite.hx:241: characters 40-47 : ... For function argument 'curFrame'
source/AtlasSprite.hx:249: characters 9-18 : Unknown identifier : relativeX
source/AtlasSprite.hx:250: characters 9-18 : Unknown identifier : relativeY
source/AtlasSprite.hx:253: characters 132-139 : Array<flixel.FlxCamera> should be Null<openfl.geom.ColorTransform>
source/AtlasSprite.hx:253: characters 132-139 : ... For optional function argument 'colorTransform'
source/AtlasSprite.hx:254: characters 22-32 : Unknown identifier : _indicator
source/AtlasSprite.hx:254: characters 22-32 : ... For function argument 'limb'

**Comment by moxie-coder** [comment] 2024-10-19 04:30
have you ran the setup file?

**Comment by KittySleeper** [comment] 2024-10-19 04:32
> have you tried flxanimate 3.0.4?

hello there memehoovy

**Comment by moxie-coder** [comment] 2024-10-19 04:33
> > have you tried flxanimate 3.0.4?
> 
> hello there memehoovy

oh hey Brandon

**Comment by ThatRozebudDude** [comment] 2024-10-19 12:21
Duplicate of #96 
Read through that, it should fix the issue.

**Comment by ModdingGaming10** [comment] 2024-10-27 15:46
Duplicate of #96 Read through that, it should fix the issue.

it don't worry

**Comment by ModdingGaming10** [comment] 2024-10-27 15:46
it don't worry

**Comment by ModdingGaming10** [comment] 2024-10-27 15:52
Warning: Lime version  may not be compatible with OpenFL openfl (expected version 7.7.0+)
Use <lime version="" /> before <haxelib name="openfl" /> to include a specific version
Warning: Lime version  may not be compatible with OpenFL 9.4.0 (expected version 7.7.0+)
Use <lime version="" /> before <haxelib name="openfl" /> to include a specific version
source/Prebuild.hx:15: Building...
 ERROR  source/funkin/graphics/video/FunkinVideoSprite.hx:4: characters 8-37

 4 | import hxcodec.flixel.FlxVideoSprite;
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   | Type not found : hxcodec.flixel.FlxVideoSprite

**Comment by ThatRozebudDude** [comment] 2024-10-27 18:21
1) Did you do everything in the other thread I linked?
2) What are you compiling because FPS Plus doesn't have a `FunkinVideoSprite.hx`

**Comment by ModdingGaming10** [comment] 2024-10-27 20:02
i can try again

**Comment by ModdingGaming10** [comment] 2024-10-27 20:48
i compiling FPS Plus

**Comment by ModdingGaming10** [comment] 2024-10-27 20:48
and i got

**Closed** 2024-11-02 14:54 UTC
